---
version: '2'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.7-management
    environment:
        RABBITMQ_DEFAULT_USER: rabbituser
        RABBITMQ_DEFAULT_PASS: rabbitpassword
    ports:
        - 5672:5672
        - 15672:15672
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=p@ssw0rd24
      - POSTGRES_USER=garuda
      - POSTGRES_DB=garuda
    ports:
      - 5432:5432
